server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  main:
   allow-circular-references: true
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/shopmedb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 814842972301-ovqeteh9qavj5arntfeu7jffson0a1bf.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
          facebook:
            client-id: 629718495145811
            client-secret: 6ea61b0b69993cfe18d5f2ffbd28e56c
            scope:
            - email
            - public_profile  
           
